website:
  title: "Paul JOnes"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd


