project:
  type: website

website:
  title: "Paul Jones' Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Education & Work"
        href: education_work.qmd
      - text: "Resume"
        href: cv.qmd

output-dir: .





