---
title: "Education and Work Experience"
format: html
---

## Education
### Grade School
I graduated at the top of my class from St. Vincent De Paul Elementary School (Kindergarten through eighth grade). From fourth through eighth grade, I won school-wide competitions in math and reading and hold all of the top three scores in the history of the accelerated reading program (where students read books independently and take tests to demonstrate comprehension). In addition, I was a year-round athlete, participating in soccer, basketball, baseball, and swimming. Despite this busy schedule, I earned an academic scholarship to St. Vincent-St. Mary High School.

### High School
I graduated from St. Vincent-St. Mary High School (STVM) with a GPA of over 4.3, ranking in the top 10 of my class. I took the most challenging courses offered, achieved the highest PSAT score (1450), and earned one of the top ACT scores in my grade (33). In addition to academics, I played soccer and basketball during my first two years and participated in varsity track and cross-country during my junior and senior years. I also earned an academic scholarship to Case Western Reserve University (CWRU).

### Undergraduate College Experience
At the time of writing, I am completing a dual major in Economics and Statistics at CWRU while pursuing a minor in Accounting. I also plan to begin a Master's degree in Accounting at CWRU. Throughout my time at Case, I have been a commuter, driving approximately one hour each way daily while balancing schoolwork, a full-time job, and supporting my fiancée.

### Graduate School
I have completed multiple graduate-level courses at CWRU and am currently in the process of enrolling in the Master's program for Accounting.

## Job Experience
### Dilly's
My first job was at a drive-in restaurant called Dilly's, where I worked full-time during the summer after high school graduation.

### Swensons
I began working at Swensons Drive-In on May 9, 2022, and have been employed there full-time ever since. Initially, I worked in the Akron market, covering locations from Montrose to Boardman and as far south as Canton and Jackson Township. In August 2024, I transferred to the Cleveland market to reduce my commute, though I still work 45 minutes to an hour from home. I have placed in the top 5 of company-wide sales competitions several times and received numerous five-star reviews for exceptional service. I have earned various awards and pins for these accomplishments.

### Internships
Throughout my college career, I have been unable to take on internships due to my full-time job at Swensons. However, the Wednesday following the publication of this website, I have an interview for an internship position in the auditing field.
